// Merges our concrete bindings (from worker-configuration.d.ts, generated by
// `wrangler types`) into OpenNext's CloudflareEnv so getCloudflareContext()
// is fully typed. Regenerate worker-configuration.d.ts after wrangler.jsonc
// binding changes via `npm run cf:typegen`.
declare global {
	interface CloudflareEnv extends Env {}
}

export {};
