-- Polling locations: the physical sites. ADA audit status lives here because
-- the audit is scoped to the location, not to any one precinct it serves.
CREATE TABLE polling_locations (
	id TEXT PRIMARY KEY,
	address TEXT NOT NULL,
	ada_audit_status TEXT NOT NULL DEFAULT 'pending'
		CHECK (ada_audit_status IN ('pending', 'compliant', 'remediated_with_kit', 'needs_relocation')),
	last_audited_at TEXT
);

-- Precincts. Multiple precincts can point at the same polling_location_id
-- (co-located precincts) — Stage 3 aggregates voter counts up to the location.
CREATE TABLE precincts (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	polling_location_id TEXT NOT NULL REFERENCES polling_locations(id),
	registered_voters INTEGER NOT NULL,
	historical_turnout REAL NOT NULL
);

CREATE INDEX idx_precincts_location ON precincts(polling_location_id);

-- Supply manifest line items generated by Stage 3. A location flagged
-- needs_relocation gets no manifest_items — it gets a review flag instead.
CREATE TABLE manifest_items (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	location_id TEXT NOT NULL REFERENCES polling_locations(id),
	item_type TEXT NOT NULL,
	quantity INTEGER NOT NULL,
	status TEXT NOT NULL DEFAULT 'pending'
);

CREATE INDEX idx_manifest_items_location ON manifest_items(location_id);

-- Confirmed allocations drawn from a shared, finite resource pool
-- (e.g. one roving ADA tech for a given date). A request that can't be
-- satisfied does not get a row here — Stage 3 surfaces it as unallocated
-- instead of writing a phantom booking.
CREATE TABLE resource_allocations (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	resource_type TEXT NOT NULL,
	date TEXT NOT NULL,
	location_id TEXT NOT NULL REFERENCES polling_locations(id),
	precinct_id TEXT REFERENCES precincts(id)
);

CREATE INDEX idx_resource_allocations_type_date ON resource_allocations(resource_type, date);
CREATE INDEX idx_resource_allocations_location ON resource_allocations(location_id);

-- Edit-provenance log behind the dashboard's structured edit form. Every
-- edit to a location's R2 audit content writes one row here.
CREATE TABLE audit_edits (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	location_id TEXT NOT NULL REFERENCES polling_locations(id),
	edited_by TEXT NOT NULL,
	edited_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
	field_changed TEXT NOT NULL,
	note TEXT
);

CREATE INDEX idx_audit_edits_location ON audit_edits(location_id);
